name: ci-cd-pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request:
    branches: main
    types: [ opened, synchronize, reopened ]

env:
  BAKEHOUSE_STACK_NAME: ${{secrets.BAKEHOUSE_STACK_NAME}}

jobs:
  run-install-script:
    name: Run install script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Check env variable
        run: echo $BAKEHOUSE_STACK_NAME

      - name: Run install script
        run: ./install.sh
